gcc 7: standarize intentional fall throughs
gcc 7 introduced the warning 'implicit-fallthrough' which makes
compilation fail:

src/cc_api/source/cc_ansic/private/rci_binary_callback.h:299:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (rci->callback.status == connector_callback_continue && remote_config->error_id == connector_success)
                ^
src/cc_api/source/cc_ansic/private/rci_binary_callback.h:309:9: note: here
         case connector_request_id_remote_config_do_command:
         ^~~~

Use the marker '// fall through' that GCC expects to avoid these errors.
Note that using ' __attribute__ ((fallthrough))' is not compatible with
older versions of GCC.

https://jira.digi.com/browse/DEL-5505

Signed-off-by: Jose Diaz de Grenu <Jose.DiazdeGrenu@digi.com>