private: rci: fix compilation error about switch case falls through statement
According to the GCC documentation, Since GCC 7 with the most stricted mode,
GCC doesn’t recognize any comments as fallthrough comments, only attributes
disable the warning.

This commit fixes the following compilation issue:

    rci_binary_callback.h:710:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
     710 |   if (rci->callback.status == connector_callback_continue
                 && remote_config->error_id == connector_success)

https://onedigi.atlassian.net/browse/DEL-7495

Signed-off-by: Arturo Buzarra <arturo.buzarra@digi.com>