connector_firmware.h: use 'connector_firmware_status_t' value to init download status
'download_request.status' is a 'connector_firmware_status_t' and not a
'fw_opcodes_t'.
Related to commit fe9642109f4817a59def43dc85e0c09017c24761.

This commit fixes the build warning:

In file included from src/cc_api/source/cc_ansic/private/connector_edp.h:43,
                 from src/cc_api/source/cc_ansic/private/connector_api.c:95:
src/cc_api/source/cc_ansic/private/connector_firmware.h: In function ‘process_fw_download_request’:
src/cc_api/source/cc_ansic/private/connector_firmware.h:462:29: error: implicit conversion from ‘enum <anonymous>’ to ‘connector_firmware_status_t’ [-Werror=enum-conversion]
  462 |     download_request.status = fw_download_abort_opcode;
      |                             ^
cc1: all warnings being treated as errors

Signed-off-by: Tatiana Leon <Tatiana.Leon@digi.com>